use_frameworks!

platform :ios, '9.0'

target 'CCBanner_Example' do
  pod 'CCBanner', :path => '../'
  pod 'Masonry', '~> 1.1.0'
  target 'CCBanner_Tests' do
    inherit! :search_paths

    
  end
end
